version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - redis
    volumes: 
      - ".:/usr/bin/backend/"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"